 name-template: 'Release v$RESOLVED_VERSION'
 tag-template: 'v$RESOLVED_VERSION'

 template: |
   ## Release v$RESOLVED_VERSION

   ### Changes
   $CHANGES

   ---

   🔗 [Compare changes](https://github.com/hello-world-boot/compare/v$PREVIOUS_TAG...v$RESOLVED_VERSION)

 change-template: '- $TITLE (#$NUMBER)'

 categories:
   - title: 'Features'
     labels:
       - 'feature'
   - title: 'Bug Fixes'
     labels:
       - 'bug'
   - title: 'Maintenance'
     labels:
       - 'chore'
       - 'refactor'
   - title: 'Breaking Changes'
     labels:
       - 'breaking-change'

 version-resolver:
   major:
     labels:
       - 'breaking-change'
   minor:
     labels:
       - 'feature'
   patch:
     labels:
       - 'bug'
       - 'chore'
       - 'refactor'
 
