name-template: 'Release v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'

categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
  - title: '🐛 Bug Fixes'
    labels:
      - 'bug'
  - title: '🛠 Maintenance'
    labels:
      - 'chore'
      - 'refactor'
change-template: '- $TITLE (#$NUMBER)'

version-resolver:
  major:
    labels: [breaking-change]
  minor:
    labels: [feature]
  patch:
    labels: [bug, chore]
